pipeline {
  agent any
  environment {
    DOCKERHUB_CRED = credentials('dockerhub') // Username + Password
    IMAGE_NAME = "vtscorpio:script-image-jenkins"
  }
  stages {
    stage('Build') {
      steps {
        sh 'sudo docker build -t $IMAGE_NAME .'
      }
    }
    stage('Login & Push') {
      steps {
        sh "echo $DOCKERHUB_CRED_PSW | docker login -u $DOCKERHUB_CRED_USR --password-stdin"
        sh 'sudo docker push $IMAGE_NAME'
      }
    }
  }
}
